source=./mango_modules/keybind.conf
source=./mango_modules/hardware.conf
source=./mango_modules/auto_start.conf
source=./mango_modules/layout_rule.conf
source=./mango_modules/window_rule.conf
source=./mango_modules/animation.conf
