animation_duration_move=150
animation_duration_open=150
animation_duration_tag=150
animation_duration_close=150

animation_type_open=zoom
animation_type_close=zoom

layerrule=animation_type_open:zoom
layerrule=animation_type_close:zoom
