# Keyboard
repeat_rate=25
repeat_delay=250
numlockon=0
xkb_rules_layout=us

# Trackpad
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
disable_while_typing=1

# Gestures
gesturebind=none,right,3,viewtoleft
gesturebind=none,left,3,viewtoright
gesturebind=SUPER,right,3,focusdir,left
gesturebind=SUPER,left,3,focusdir,right
gesturebind=none,up,3,toggleoverview
