
bind=SUPER+SHIFT,r,reload_config
bind=SUPER,q,killclient
# Launch app
bind=SUPER,r,spawn_shell,pkill rofi || rofi -show drun
bind=SUPER,Return,spawn,$TERMINAL
bind=SUPER,b,spawn,brave-origin
bind=SUPER,e,spawn,$TERMINAL bash -c -l yazi
bind=SUPER,c,spawn,$TERMINAL bash -c -l nvim
bind=SUPER,a,spawn,~/.config/scripts/launch_wiremix.sh
bind=SUPER,w,spawn,~/.config/scripts/launch_impala.sh
bind=SUPER,x,spawn,~/.config/scripts/launch_bluetui.sh

# Util 
bind=SUPER,p,spawn,~/.config/scripts/powermode_switch.sh
bind=SUPER,Escape,spawn_shell,pkill rofi ||  ~/.config/rofi/powermenu_mango.sh
bind=SUPER,f,switch_proportion_preset
bind=SUPER+SHIFT,x,spawn_shell,g=$(slurp -d) && [ -n "$g" ] && f=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grim -g "$g" "$f" && wl-copy < "$f" && notify-send "Region captured & copied !"
bind=NONE,Print,spawn_shell,f=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grim -c "$f" && wl-copy < "$f" && notify-send "Screen captured & copied !"
bind=SUPER,i,spawn,~/.config/scripts/launch-rofi-images.sh
bind=SUPER,d,spawn_shell,$TERMINAL bash -c -i db
# Volume
bind=SUPER,F1,spawn_shell,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && ~/.config/scripts/audio.sh
bind=SUPER,F2,spawn_shell,wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%- && ~/.config/scripts/audio.sh
bind=SUPER,F3,spawn_shell,wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && ~/.config/scripts/audio.sh

# Brightnesss
bind=SUPER,F9,spawn_shell,brightnessctl set 5%- && ~/.config/scripts/screen_brightness.sh
bind=SUPER,F10,spawn_shell,brightnessctl set 5%+ && ~/.config/scripts/screen_brightness.sh

# Navigate window
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up

bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Down,focusdir,down
bind=SUPER,Up,focusdir,up

bind=SUPER+CTRL,l,exchange_client,right
bind=SUPER+CTRL,h,exchange_client,left

bind=SUPER+CTRL,Right,exchange_client,right
bind=SUPER+CTRL,Left,exchange_client,Left
# Move window to tag
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0

# Navigate tag (workspace)
bind=SUPER+SHIFT,h,viewtoleft,0
bind=SUPER+SHIFT,l,viewtoright,0

bind=SUPER+SHIFT,Left,viewtoleft,0
bind=SUPER+SHIFT,Right,viewtoleft,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0

# Lid event
switchbind=fold,spawn_shell,systemctl suspend && hyprlock
