tagrule=id:1,layout_name:scroller,no_hide:1
tagrule=id:2,layout_name:scroller,no_hide:1
tagrule=id:3,layout_name:scroller,no_hide:1
tagrule=id:4,layout_name:scroller,no_hide:1
tagrule=id:5,layout_name:scroller,no_hide:1

scroller_structs=0
scroller_proportion_preset=1.0,0.5,0.3
scroller_default_proportion=0.5
scroller_default_proportion_single=1.0
scroller_ignore_proportion_single=0
