border_radius=5
borderpx=2
focuscolor=b56cffff
maximizescreencolor=b56cffff
gappih=2
gappiv=2
gappoh=2
gappov=2

windowrule=isfloating:1,width:800,height:600,offsetx:0,offsety:0,title:(wiremix|impala|bluetui)
