background {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/wallpaper1.jpg
    blur_passes = 2
    blur_size = 6
    noise = 0.02
    contrast = 1.0
    brightness = 0.7
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true

    outer_color = rgba(b29cc6ff)
    inner_color = rgba(1a1a1acc)
    font_color = rgba(ffffffff)


    fade_on_empty = false
    rounding = 12

    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    update = 1000
    text = $TIME
    color = rgba(ffffffff)

    font_size = 75
    font_family = JetBrainsMono Nerd Font Mono SemiBold

    position = 0, 120
    halign = center
    valign = center
}

# ==============================
# General
# ==============================

general {
    hide_cursor = true
    ignore_empty_input = true
}
