font_family monospace

background #1d1325
background_opacity 0.9
window_padding_width 5
font_size 11
confirm_os_window_close 0
cursor_trail 2

pixel_scroll yes
momentum_scroll 0.96

tab_bar_style powerline
tab_powerline_style round

active_tab_foreground #1d1325
active_tab_background #b29cc6
inactive_tab_background #322140
inactive_tab_foreground #b29cc6

map alt+n new_tab
map alt+l next_tab
map alt+h previous_tab
map alt+q close_tab
map alt+right next_tab
map alt+left previous_tab
map alt+r set_tab_title
